service: serverless-s3-local-example

provider:
  name: aws
  runtime: python3.8

plugins:
  - serverless-s3-local
  - serverless-offline

custom:
  s3:
    port: 8000
    directory: /tmp

functions:
  webhook:
    handler: handler.webhook
    events:
      - http:
          path: /
          method: get
  s3hook:
    handler: handler.s3hook
    events:
      - s3: local-bucket
